ALTER SESSION SET CONTAINER = XEPDB1;

-- Recompile schema
BEGIN DBMS_UTILITY.compile_schema(USER,FALSE); END;
/
SHOW ERRORS

-- Set user passwords
ALTER USER DELIUS_APP_SCHEMA IDENTIFIED BY &1;
ALTER USER DELIUS_APP_SCHEMA ACCOUNT UNLOCK;
ALTER USER DELIUS_POOL IDENTIFIED BY &1;
ALTER USER DELIUS_POOL ACCOUNT UNLOCK;
COMMIT;

EXIT;