ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE T_DATA DATAFILE '/opt/oracle/oradata/XE/XEPDB1/T_DATA.dbf' SIZE 100M AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE T_REFERENCE_DATA DATAFILE '/opt/oracle/oradata/XE/XEPDB1/T_REFERENCE_DATA.dbf' SIZE 100M AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE T_AUDIT_DATA DATAFILE '/opt/oracle/oradata/XE/XEPDB1/T_AUDIT_DATA.dbf' SIZE 100M AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE T_AUDINT_DATA DATAFILE '/opt/oracle/oradata/XE/XEPDB1/T_AUDINT_DATA.dbf' SIZE 100M AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE T_SPG_DATA DATAFILE '/opt/oracle/oradata/XE/XEPDB1/T_SPG_DATA.dbf' SIZE 100M AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE T_DOCUMENT_DATA DATAFILE '/opt/oracle/oradata/XE/XEPDB1/T_DOCUMENT_DATA.dbf' SIZE 100M AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE T_CHANGE_CAPTURE_DATA DATAFILE '/opt/oracle/oradata/XE/XEPDB1/T_CHANGE_CAPTURE_DATA.dbf' SIZE 100M AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE CFO_DATA DATAFILE '/opt/oracle/oradata/XE/XEPDB1/CFO_DATA.dbf' SIZE 100M AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE CFO_INDEX DATAFILE '/opt/oracle/oradata/XE/XEPDB1/CFO_INDEX.dbf' SIZE 100M AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE OR REPLACE DIRECTORY IMPORT_DIR AS '/datapump';
CREATE OR REPLACE DIRECTORY APS_DIR AS '/tmp';

EXIT;